nocox/asakatu-kun

README.md

fix #12 
README.mdにWikiのAPIページへのリンクを記述した
-
-
-

APIを書いたWikiをREADMEに貼った

---

README.md

fix #45 
環境構築くらいREADMEに欲しい、Wikiへの導線作成のため
README.mdにWikiの環境構築ページへのリンクを記述した
-
-
-

環境立てる方法を書いたWikiをREADMEに貼った

---

frontend/index.html

#46 
HTMLファイル作る時の共通項目の定義。
主にヘッダー部分。具体的な内容は今後デザインとかがかたまり次第追記で。
- 明らかに不要なものがあれば削る
- 具体的な内容は今後追記していきます。
- 具体的な内容（アイコンとか）

HTML templateとりあえず仮置き

---

frontend/README.md
frontend/index.html

#48 
段階的にVUEを導入するためにまずはCDNを記述。
CDNのリンクをテンプレートのヘッダーに追記
- コンソールでVUEの記述がでてくるか
- 開発環境を整えただけです。
- 開発していきます。

VUEのCDNのリンクを追記します。

---

frontend/assets/stylesheet/main.css
frontend/event.html

#37 
コーディングだけ先にやってしまいます。
HTMLだけ書きます。

イベント詳細ページのコーディング

---

springboot/src/main/resources/schema-product.sql

なし
開発中．起動のたびに登録したユーザ情報が消えるのは面倒なので
schema-product.sql内のdorpを 削除
dbを初期化したい場合は，コンテナを再起動してね
```
docker-compose down
docker-compose up db
```
-
-
-

[IR] springboot起動時にテーブルを毎回dropする設定を修正

---

vue/src/App.vue
vue/tests/e2e/specs/SignUpTest.js
vue/tests/e2e/specs/test.js

たぶんない。
今後の実装を進めるにあたりE2Eテストできるようにしておく。
-
-
-

[WIP]Vueのテストを書いてみます。

---

springboot/src/main/java/hello/OkResponse.java
springboot/src/main/java/hello/controller/EventController.java
springboot/src/main/java/hello/controller/UserRegistrationController.java

fix #75
OkResponseが重複していた
OkResponseをクラスに切り出しました
- 切り出し方が正しいか？

[IR]OkResponseを切り出した

---

frontend/assets/javascript/event.js
frontend/event.html
frontend/index.html

#
APIから情報を取ってきて表示する。
非同期に最初から対応させます。
-
- URL対応はまだです。
-

イベント詳細ページのAPI処理

---

springboot/src/main/java/com/asakatu/controller/EventController.java
springboot/src/main/java/com/asakatu/entity/User.java
springboot/src/main/java/com/asakatu/entity/UserStatus.java
springboot/src/main/java/com/asakatu/response/GetEventsListResponse.java
springboot/src/test/java/com/asakatu/EventControllerTests.java
springboot/src/test/resources/data-product.sql

#74 
manyTomanyの影響で`/events`がたくさん出ていた問題を修正しました。
`duraution`がいらない問題とかは触れていません
もうちょい色々変更したいので、マージしてもいいし、マージしなくてもいいです
- なんかもっと良い方法ある気がする
-
-

イベント一覧がたくさん出てたのを修正

---

vue/src/views/EventCreate.vue

イベント投稿機能の作製

---

vue/src/router.js
vue/src/views/About.vue
vue/src/views/Event.vue
vue/src/views/EventCreate.vue
vue/src/views/Events.vue

フロント側のリファクタ

---

springboot/src/main/java/com/asakatu/WebSecurityConfig.java
vue/src/views/SignUp.vue
vue/vue.config.js

フロント側からサインアップできる様に修正していく
-
-
-

フロントのサインアップ機能の修正

---

vue/src/App.vue
vue/src/router.js
vue/src/store.js
vue/src/views/Login.vue
vue/src/views/MyPage.vue

フロント側でマイページを作製します。
自分の情報の表示や、自分の情報の編集ができるページを用意します。
-
-
-

フロント、マイページの作製

---

vue/src/store.js
vue/src/views/Login.vue

マイページとログイン周りの修正

---

vue/src/App.vue
vue/src/assets/css/_login-signup.scss
vue/src/components/HelloWorld.vue
vue/src/views/Login.vue
vue/src/views/SignUp.vue

#35 
田島氏が作ってくれたデザインをvueに適応する作業を行います。
もともとつくってあったvueのmethodに合うように書き換えます。
- スタイリングが適応されているかどうか
- バリデーションを大きく変える必要がある
- バックエンド（API）がわのレスポンスに対応してエラーメッセージを表示すうる仕様に変える必要がある。

ログイン周りのデザインを適応

---

springboot/src/main/java/com/asakatu/controller/EventController.java
springboot/src/main/java/com/asakatu/controller/ReactionController.java
springboot/src/main/java/com/asakatu/controller/UserDetailController.java
springboot/src/main/java/com/asakatu/controller/UserRegistrationController.java
springboot/src/main/java/com/asakatu/entity/UserStatusMaster.java
springboot/src/main/java/com/asakatu/exeptions/FileStorageException.java
springboot/src/main/java/com/asakatu/property/S3ProfileImageProperties.java
springboot/src/main/java/com/asakatu/property/S3ReactionImageProperties.java
springboot/src/main/java/com/asakatu/repository/UserStatusMasterRepository.java
springboot/src/main/java/com/asakatu/response/GetListResponse.java
springboot/src/main/java/com/asakatu/response/ObjectResponse.java
springboot/src/main/java/com/asakatu/service/ProfileImageService.java
springboot/src/main/java/com/asakatu/service/S3BucketService.java
springboot/src/main/resources/application.yml
springboot/src/main/resources/schema-product.sql
springboot/src/test/java/com/asakatu/ReactionControllerTests.java
springboot/src/test/resources/data-product.sql
vue/src/components/ReactionList.vue
vue/src/components/UserReaction.vue
vue/src/router.js
vue/src/store.js
vue/src/views/ComponentDemo.vue
vue/vue.config.js

- fix: #109
ユーザは，イベントごとでリアクションを持つことができ，表示，変更ができる．
ユーザのリアクションは，元々画像で行う予定だったが，絵文字で良いのではと思いこちらの実装にしました．
S3画像に関しても，DBに保存するコンテンツ情報をURLに変更するだけで対応できる．併用も少しの工夫で可能．
- 絵文字を利用することについて
- Issueでは，コメントと記述されているが，このプルリクではリアクションで統一している．
- S3を利用する方法で途中まで開発していたので，S3関連のリファクタリングもスコープ内に入ってます．
-
ユーザ登録
```
curl -X POST -H "Content-Type: application/json" -d '{"username":"tester7er", "password":"aabbcc2aaaaaaa", "displayName":"abc", "email":"aaa@bbbb.com", "passwordConfirm":"aabbcc2aaaaaaa"}' -i localhost:8080/user_registration
```
ログイン
```
curl -i -c cookie.txt -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "username=tester7er" -d "password=aabbcc2aaaaaaa" "http://localhost:8080/login"
```
event作成
```
curl -b cookie.txt -X POST -H "Content-Type: application/json" -d …
```

[IR] リアクションの表示と変更

---

vue/src/store.js
vue/src/views/Login.vue
vue/src/views/MyPage.vue

- #137 
ログインが正常に動作していなかったので修正
今後の実装でログイン前提の処理を実装していくので，早めに解決したかった．
vueの動作環境は用意してね
- 
- 今回わかりやすさのため，一時的にログイン先をmypageにしています(本来はイベント一覧ページ)
-

[IR] ログインが正常に動作するように修正

---

vue/src/components/header.vue
vue/src/views/Home.vue

[IR] headerをcomponentにしたよ

---

frontend/assets/img/Bizspot.svg
frontend/assets/stylesheet/events.css
frontend/events.html

Eventsview

---

frontend/assets/img/Bizspot.svg
frontend/assets/stylesheet/events.css
frontend/events.html

なんで空コミットすんだし？

---

springboot/src/test/java/com/asakatu/UserRegistrationControllerTests.java

なし
落ちてたので修正しました！
どっかのタイミングでの修正漏れだと思われ
-
-
-

test: UserRegistrationControllerTestsを修正

---

springboot/src/main/java/com/asakatu/controller/EventController.java
springboot/src/main/java/com/asakatu/entity/Event.java
springboot/src/main/java/com/asakatu/property/FromFrontEventProperties.java
springboot/src/main/resources/schema-product.sql
springboot/src/test/java/com/asakatu/EventControllerTests.java
springboot/src/test/resources/data-product.sql
vue/src/views/EventCreate.vue

store_nameを追加
